name: rainnet
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - h5py
  - pandas
  - xarray
  - netcdf4
  - pillow
  - matplotlib
  - requests
  - wradlib
  - cartopy
  - rasterio
  - rioxarray
  - gdal
  - pyproj
  - shapely
  - pip:
      - tensorflow==2.20.0
      - tensorboard==2.20.0
      - xradar==0.10.0
      - cmweather==0.3.2